### ISSUE TITLE
Doesn’t work. 

### ISSUE THREAD

**Issue by iammanpreetsingh** [Renaitare/Notations#2]
Nothing happens when I double tap the stausbar. It just dims my homescreen. I tap and hold the screen but still nothing.

iPhone 8
iOS13.3 checkra1n

**Comment by iD7me** [comment]
After dimmed screen tap and hold on the middle of the screen it should work now.

**Comment by tale** [comment]
Duplicate of #1 lmao.... yeah just make sure to tap and hold to create a note!
