### ISSUE TITLE
1.0.0-63 version

### ISSUE THREAD

**Issue by iD7me** [Renaitare/Notations#7]
Nice update 👍🏻, now Notations work in every app but I can't hide the note sticker by double-tap like before! Now I have to swipe up from the bottom to disable it and this force me to go to the homescreen.

**Comment by Skittyblock** [comment]
You can also press the power button to disable it. Additionally, I just added a tap gesture to the background to dismiss, so you'll be able to use that in the next update.

**Comment by iD7me** [comment]
Great.
